SELECT * FROM EMPLOYEE;   -- CTR ENTER TO EXECUTE 
 
select COUNT(*) AS COUNT FROM EMPLOYEE;

DELETE FROM EMPLOYEE ;

DELETE FROM EMPLOYEE WHERE EmpID = 'EMP-10032';
-- TO REMOVE SAFE MODE, >> EDIT .. PREFERENCE .. SQL EDITOR ... UNTICK ; SAFE MODE
-- RESTART THE DBMS

ALTER TABLE EMPLOYEE RENAME COLUMN ï»¿EmpID TO EmpID;


-- GROUPBY , HAVING , DROP, ALTER ( ADD, MODIFY, DROP)  ,, SQL JOINS 

SELECT * FROM EMPLOYEE;

SELECT CITY FROM EMPLOYEE;
SELECT DISTINCT CITY FROM EMPLOYEE ;
SELECT CITY FROM EMPLOYEE GROUP BY CITY;

SELECT CITY , COUNT(CITY) AS COUNT FROM EMPLOYEE GROUP BY CITY;

SELECT CITY ,SUM(SALARY), AVG(SALARY) ,COUNT(CITY)   FROM EMPLOYEE GROUP BY CITY;

SELECT GENDER, COUNT(*) AS COUNT FROM employee GROUP BY GENDER;

SELECT City  FROM EMPLOYEE WHERE CITY IN ( 'PUNE', 'KANPUR') ;  -- WHERE WORK ON RAW DATA

SELECT CITY,GENDER,  COUNT(*) AS COUNT FROM employee GROUP BY CITY ,GENDER  HAVING CITY IN ( 'PUNE', 'KANPUR' ,'MUMBAI')  ;  -- HAVING WORK ON RESULT OF GROUP BY

SELECT CITY,GENDER,  COUNT(*) AS COUNT FROM employee GROUP BY CITY ,GENDER  HAVING CITY IN ( 'PUNE', 'KANPUR' ,'MUMBAI') AND GENDER = 'M' ;

-- ALTER TABLE EMPLOYEE DROP COLUMN HireDate ;

-- ALTER TABLE EMPLOYEE ADD COLUMN HireDate datetime;


SELECT * FROM EMPLOYEE;

SELECT [Date of Hire]  from Employee;